"""phase3 practice sessions

Revision ID: ba35d4c616d6
Revises: 0002_phase2_reference_data
Create Date: 2026-09-28 09:33:31.845237

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ba35d4c616d6'
down_revision: str | Sequence[str] | None = '0002_phase2_reference_data'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('language_profile_id', sa.Uuid(), nullable=False),
    sa.Column('training_mode', sa.Enum('conversation', 'professional', 'scenario', 'free_talk', name='training_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('communication_register_id', sa.Integer(), nullable=False),
    sa.Column('profile_cefr_snapshot', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='profile_cefr_snapshot', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_cefr', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='target_cefr', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('scenario_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='session_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'active'\n                AND ended_at IS NULL\n            )\n            OR\n            (\n                status IN ('completed', 'abandoned')\n                AND ended_at IS NOT NULL\n            )\n            ", name=op.f('ck_practice_sessions_status_matches_ended_at')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_practice_sessions_ended_at_not_before_started_at')),
    sa.ForeignKeyConstraint(['communication_register_id'], ['communication_registers.id'], name=op.f('fk_practice_sessions_communication_register_id_communication_registers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['language_profile_id'], ['language_profiles.id'], name=op.f('fk_practice_sessions_language_profile_id_language_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sessions'))
    )
    op.create_index(op.f('ix_practice_sessions_language_profile_id'), 'practice_sessions', ['language_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_sessions_language_profile_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###
